/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as ExplanationAssessmentRouteImport } from './routes/explanation-assessment'
import { Route as TacticalSprintRouteImport } from './routes/tactical-sprint'
import { Route as TransferTestRouteImport } from './routes/transfer-test'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as CurriculumConceptSlugRouteImport } from './routes/curriculum/$conceptSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplanationAssessmentRoute = ExplanationAssessmentRouteImport.update({
  id: '/explanation-assessment',
  path: '/explanation-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticalSprintRoute = TacticalSprintRouteImport.update({
  id: '/tactical-sprint',
  path: '/tactical-sprint',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferTestRoute = TransferTestRouteImport.update({
  id: '/transfer-test',
  path: '/transfer-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumConceptSlugRoute = CurriculumConceptSlugRouteImport.update({
  id: '/curriculum/$conceptSlug',
  path: '/curriculum/$conceptSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/explanation-assessment': typeof ExplanationAssessmentRoute
  '/tactical-sprint': typeof TacticalSprintRoute
  '/transfer-test': typeof TransferTestRoute
  '/api/health': typeof ApiHealthRoute
  '/curriculum/$conceptSlug': typeof CurriculumConceptSlugRoute
  '/curriculum/': typeof CurriculumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/explanation-assessment': typeof ExplanationAssessmentRoute
  '/tactical-sprint': typeof TacticalSprintRoute
  '/transfer-test': typeof TransferTestRoute
  '/api/health': typeof ApiHealthRoute
  '/curriculum/$conceptSlug': typeof CurriculumConceptSlugRoute
  '/curriculum': typeof CurriculumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/explanation-assessment': typeof ExplanationAssessmentRoute
  '/tactical-sprint': typeof TacticalSprintRoute
  '/transfer-test': typeof TransferTestRoute
  '/api/health': typeof ApiHealthRoute
  '/curriculum/$conceptSlug': typeof CurriculumConceptSlugRoute
  '/curriculum/': typeof CurriculumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concepts'
    | '/explanation-assessment'
    | '/tactical-sprint'
    | '/transfer-test'
    | '/api/health'
    | '/curriculum/$conceptSlug'
    | '/curriculum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concepts'
    | '/explanation-assessment'
    | '/tactical-sprint'
    | '/transfer-test'
    | '/api/health'
    | '/curriculum/$conceptSlug'
    | '/curriculum'
  id:
    | '__root__'
    | '/'
    | '/concepts'
    | '/explanation-assessment'
    | '/tactical-sprint'
    | '/transfer-test'
    | '/api/health'
    | '/curriculum/$conceptSlug'
    | '/curriculum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptsRoute: typeof ConceptsRoute
  ExplanationAssessmentRoute: typeof ExplanationAssessmentRoute
  TacticalSprintRoute: typeof TacticalSprintRoute
  TransferTestRoute: typeof TransferTestRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CurriculumConceptSlugRoute: typeof CurriculumConceptSlugRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explanation-assessment': {
      id: '/explanation-assessment'
      path: '/explanation-assessment'
      fullPath: '/explanation-assessment'
      preLoaderRoute: typeof ExplanationAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactical-sprint': {
      id: '/tactical-sprint'
      path: '/tactical-sprint'
      fullPath: '/tactical-sprint'
      preLoaderRoute: typeof TacticalSprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer-test': {
      id: '/transfer-test'
      path: '/transfer-test'
      fullPath: '/transfer-test'
      preLoaderRoute: typeof TransferTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$conceptSlug': {
      id: '/curriculum/$conceptSlug'
      path: '/curriculum/$conceptSlug'
      fullPath: '/curriculum/$conceptSlug'
      preLoaderRoute: typeof CurriculumConceptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptsRoute: ConceptsRoute,
  ExplanationAssessmentRoute: ExplanationAssessmentRoute,
  TacticalSprintRoute: TacticalSprintRoute,
  TransferTestRoute: TransferTestRoute,
  ApiHealthRoute: ApiHealthRoute,
  CurriculumConceptSlugRoute: CurriculumConceptSlugRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
